---
- name: "[EL] Enable CRB repository"
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: "[EL] Enable EPEL repository"
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: "[EL] Update package cache"
  ansible.builtin.dnf:
    update_cache: true
  changed_when: false
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: "[EL] Install system packages"
  ansible.builtin.dnf:
    name:
      - supervisor
      - openssl
      - python3
      - bridge-utils
      - curl
      - openssl-devel
      - libffi-devel
      - "@Development Tools"
      - cronie
      - NetworkManager
      - wireguard-tools
    state: latest
    allowerasing: true
  ignore_errors: true
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: "[EL] Install acl if acting as non-root user"
  ansible.builtin.dnf:
    name: acl
  when: ansible_user is not defined or ansible_user != 'root'
  retries: 5
  delay: 10
  register: result
  until: result is success
  ignore_errors: true

- name: "[EL] Ensure supervisord is started"
  ansible.builtin.service:
    name: supervisord
    state: started
    enabled: true

- name: "[EL] Install python3 packages"
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-devel
  retries: 5
  delay: 10
  register: result
  until: result is success

- name: "[EL] Check virtualenv"
  block:
    - name: "[EL] Check virtualenv executable path"
      ansible.builtin.command: which virtualenv
      register: virtualenv_output
      changed_when: false
    - name: "[EL] Test virtualenv executable path not empty"
      ansible.builtin.fail:
      when: virtualenv_output | length == 0
      changed_when: false
  rescue:
    - name: "[EL] Install virtualenv system package"
      ansible.builtin.dnf:
        name: virtualenv
        state: latest